# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: s3/S3StorageService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from airavata_mft_sdk.s3 import S3Storage_pb2 as s3_dot_S3Storage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19s3/S3StorageService.proto\x12+org.apache.airavata.mft.resource.service.s3\x1a\x12s3/S3Storage.proto2\xc1\x06\n\x10S3StorageService\x12\xa2\x01\n\rlistS3Storage\x12G.org.apache.airavata.mft.resource.stubs.s3.storage.S3StorageListRequest\x1aH.org.apache.airavata.mft.resource.stubs.s3.storage.S3StorageListResponse\x12\x94\x01\n\x0cgetS3Storage\x12\x46.org.apache.airavata.mft.resource.stubs.s3.storage.S3StorageGetRequest\x1a<.org.apache.airavata.mft.resource.stubs.s3.storage.S3Storage\x12\x9a\x01\n\x0f\x63reateS3Storage\x12I.org.apache.airavata.mft.resource.stubs.s3.storage.S3StorageCreateRequest\x1a<.org.apache.airavata.mft.resource.stubs.s3.storage.S3Storage\x12\xa8\x01\n\x0fupdateS3Storage\x12I.org.apache.airavata.mft.resource.stubs.s3.storage.S3StorageUpdateRequest\x1aJ.org.apache.airavata.mft.resource.stubs.s3.storage.S3StorageUpdateResponse\x12\xa8\x01\n\x0f\x64\x65leteS3Storage\x12I.org.apache.airavata.mft.resource.stubs.s3.storage.S3StorageDeleteRequest\x1aJ.org.apache.airavata.mft.resource.stubs.s3.storage.S3StorageDeleteResponseB\x02P\x01\x62\x06proto3')



_S3STORAGESERVICE = DESCRIPTOR.services_by_name['S3StorageService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _S3STORAGESERVICE._serialized_start=95
  _S3STORAGESERVICE._serialized_end=928
# @@protoc_insertion_point(module_scope)
