# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: azure/AzureSecretService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from airavata_mft_sdk.azure import AzureCredential_pb2 as azure_dot_AzureCredential__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61zure/AzureSecretService.proto\x12\x30org.apache.airavata.mft.credential.service.azure\x1a\x1b\x61zure/AzureCredential.proto2\x9e\x05\n\x12\x41zureSecretService\x12\x94\x01\n\x0egetAzureSecret\x12\x45.org.apache.airavata.mft.credential.stubs.azure.AzureSecretGetRequest\x1a;.org.apache.airavata.mft.credential.stubs.azure.AzureSecret\x12\x9a\x01\n\x11\x63reateAzureSecret\x12H.org.apache.airavata.mft.credential.stubs.azure.AzureSecretCreateRequest\x1a;.org.apache.airavata.mft.credential.stubs.azure.AzureSecret\x12\xa8\x01\n\x11updateAzureSecret\x12H.org.apache.airavata.mft.credential.stubs.azure.AzureSecretUpdateRequest\x1aI.org.apache.airavata.mft.credential.stubs.azure.AzureSecretUpdateResponse\x12\xa8\x01\n\x11\x64\x65leteAzureSecret\x12H.org.apache.airavata.mft.credential.stubs.azure.AzureSecretDeleteRequest\x1aI.org.apache.airavata.mft.credential.stubs.azure.AzureSecretDeleteResponseB\x02P\x01\x62\x06proto3')



_AZURESECRETSERVICE = DESCRIPTOR.services_by_name['AzureSecretService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _AZURESECRETSERVICE._serialized_start=114
  _AZURESECRETSERVICE._serialized_end=784
# @@protoc_insertion_point(module_scope)
