# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from airavata_mft_sdk.azure import AzureStorage_pb2 as azure_dot_AzureStorage__pb2


class AzureStorageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.listAzureStorage = channel.unary_unary(
                '/org.apache.airavata.mft.resource.service.azure.AzureStorageService/listAzureStorage',
                request_serializer=azure_dot_AzureStorage__pb2.AzureStorageListRequest.SerializeToString,
                response_deserializer=azure_dot_AzureStorage__pb2.AzureStorageListResponse.FromString,
                )
        self.getAzureStorage = channel.unary_unary(
                '/org.apache.airavata.mft.resource.service.azure.AzureStorageService/getAzureStorage',
                request_serializer=azure_dot_AzureStorage__pb2.AzureStorageGetRequest.SerializeToString,
                response_deserializer=azure_dot_AzureStorage__pb2.AzureStorage.FromString,
                )
        self.createAzureStorage = channel.unary_unary(
                '/org.apache.airavata.mft.resource.service.azure.AzureStorageService/createAzureStorage',
                request_serializer=azure_dot_AzureStorage__pb2.AzureStorageCreateRequest.SerializeToString,
                response_deserializer=azure_dot_AzureStorage__pb2.AzureStorage.FromString,
                )
        self.updateAzureStorage = channel.unary_unary(
                '/org.apache.airavata.mft.resource.service.azure.AzureStorageService/updateAzureStorage',
                request_serializer=azure_dot_AzureStorage__pb2.AzureStorageUpdateRequest.SerializeToString,
                response_deserializer=azure_dot_AzureStorage__pb2.AzureStorageUpdateResponse.FromString,
                )
        self.deleteAzureStorage = channel.unary_unary(
                '/org.apache.airavata.mft.resource.service.azure.AzureStorageService/deleteAzureStorage',
                request_serializer=azure_dot_AzureStorage__pb2.AzureStorageDeleteRequest.SerializeToString,
                response_deserializer=azure_dot_AzureStorage__pb2.AzureStorageDeleteResponse.FromString,
                )


class AzureStorageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def listAzureStorage(self, request, context):
        """Storage

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAzureStorage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createAzureStorage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateAzureStorage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteAzureStorage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AzureStorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'listAzureStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.listAzureStorage,
                    request_deserializer=azure_dot_AzureStorage__pb2.AzureStorageListRequest.FromString,
                    response_serializer=azure_dot_AzureStorage__pb2.AzureStorageListResponse.SerializeToString,
            ),
            'getAzureStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.getAzureStorage,
                    request_deserializer=azure_dot_AzureStorage__pb2.AzureStorageGetRequest.FromString,
                    response_serializer=azure_dot_AzureStorage__pb2.AzureStorage.SerializeToString,
            ),
            'createAzureStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.createAzureStorage,
                    request_deserializer=azure_dot_AzureStorage__pb2.AzureStorageCreateRequest.FromString,
                    response_serializer=azure_dot_AzureStorage__pb2.AzureStorage.SerializeToString,
            ),
            'updateAzureStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.updateAzureStorage,
                    request_deserializer=azure_dot_AzureStorage__pb2.AzureStorageUpdateRequest.FromString,
                    response_serializer=azure_dot_AzureStorage__pb2.AzureStorageUpdateResponse.SerializeToString,
            ),
            'deleteAzureStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteAzureStorage,
                    request_deserializer=azure_dot_AzureStorage__pb2.AzureStorageDeleteRequest.FromString,
                    response_serializer=azure_dot_AzureStorage__pb2.AzureStorageDeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'org.apache.airavata.mft.resource.service.azure.AzureStorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AzureStorageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def listAzureStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/org.apache.airavata.mft.resource.service.azure.AzureStorageService/listAzureStorage',
            azure_dot_AzureStorage__pb2.AzureStorageListRequest.SerializeToString,
            azure_dot_AzureStorage__pb2.AzureStorageListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getAzureStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/org.apache.airavata.mft.resource.service.azure.AzureStorageService/getAzureStorage',
            azure_dot_AzureStorage__pb2.AzureStorageGetRequest.SerializeToString,
            azure_dot_AzureStorage__pb2.AzureStorage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createAzureStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/org.apache.airavata.mft.resource.service.azure.AzureStorageService/createAzureStorage',
            azure_dot_AzureStorage__pb2.AzureStorageCreateRequest.SerializeToString,
            azure_dot_AzureStorage__pb2.AzureStorage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def updateAzureStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/org.apache.airavata.mft.resource.service.azure.AzureStorageService/updateAzureStorage',
            azure_dot_AzureStorage__pb2.AzureStorageUpdateRequest.SerializeToString,
            azure_dot_AzureStorage__pb2.AzureStorageUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteAzureStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/org.apache.airavata.mft.resource.service.azure.AzureStorageService/deleteAzureStorage',
            azure_dot_AzureStorage__pb2.AzureStorageDeleteRequest.SerializeToString,
            azure_dot_AzureStorage__pb2.AzureStorageDeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
