# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from airavata_mft_sdk.common import StorageCommon_pb2 as common_dot_StorageCommon__pb2


class StorageCommonServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.resolveStorageType = channel.unary_unary(
                '/org.apache.airavata.mft.resource.stubs.storage.common.StorageCommonService/resolveStorageType',
                request_serializer=common_dot_StorageCommon__pb2.StorageTypeResolveRequest.SerializeToString,
                response_deserializer=common_dot_StorageCommon__pb2.StorageTypeResolveResponse.FromString,
                )


class StorageCommonServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def resolveStorageType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageCommonServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'resolveStorageType': grpc.unary_unary_rpc_method_handler(
                    servicer.resolveStorageType,
                    request_deserializer=common_dot_StorageCommon__pb2.StorageTypeResolveRequest.FromString,
                    response_serializer=common_dot_StorageCommon__pb2.StorageTypeResolveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'org.apache.airavata.mft.resource.stubs.storage.common.StorageCommonService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StorageCommonService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def resolveStorageType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/org.apache.airavata.mft.resource.stubs.storage.common.StorageCommonService/resolveStorageType',
            common_dot_StorageCommon__pb2.StorageTypeResolveRequest.SerializeToString,
            common_dot_StorageCommon__pb2.StorageTypeResolveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
