# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: box/BoxCredential.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import airavata_mft_sdk.CredCommon_pb2 as CredCommon__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x62ox/BoxCredential.proto\x12,org.apache.airavata.mft.credential.stubs.box\x1a\x10\x43redCommon.proto\"2\n\tBoxSecret\x12\x10\n\x08secretId\x18\x01 \x01(\t\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x02 \x01(\t\"f\n\x13\x42oxSecretGetRequest\x12\x10\n\x08secretId\x18\x01 \x01(\t\x12=\n\nauthzToken\x18\x02 \x01(\x0b\x32).org.apache.airavata.mft.common.AuthToken\"l\n\x16\x42oxSecretCreateRequest\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x01 \x01(\t\x12=\n\nauthzToken\x18\x02 \x01(\x0b\x32).org.apache.airavata.mft.common.AuthToken\"~\n\x16\x42oxSecretUpdateRequest\x12\x10\n\x08secretId\x18\x01 \x01(\t\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x02 \x01(\t\x12=\n\nauthzToken\x18\x03 \x01(\x0b\x32).org.apache.airavata.mft.common.AuthToken\"+\n\x17\x42oxSecretUpdateResponse\x12\x10\n\x08secretId\x18\x01 \x01(\t\"i\n\x16\x42oxSecretDeleteRequest\x12\x10\n\x08secretId\x18\x01 \x01(\t\x12=\n\nauthzToken\x18\x02 \x01(\x0b\x32).org.apache.airavata.mft.common.AuthToken\")\n\x17\x42oxSecretDeleteResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x42\x02P\x01\x62\x06proto3')



_BOXSECRET = DESCRIPTOR.message_types_by_name['BoxSecret']
_BOXSECRETGETREQUEST = DESCRIPTOR.message_types_by_name['BoxSecretGetRequest']
_BOXSECRETCREATEREQUEST = DESCRIPTOR.message_types_by_name['BoxSecretCreateRequest']
_BOXSECRETUPDATEREQUEST = DESCRIPTOR.message_types_by_name['BoxSecretUpdateRequest']
_BOXSECRETUPDATERESPONSE = DESCRIPTOR.message_types_by_name['BoxSecretUpdateResponse']
_BOXSECRETDELETEREQUEST = DESCRIPTOR.message_types_by_name['BoxSecretDeleteRequest']
_BOXSECRETDELETERESPONSE = DESCRIPTOR.message_types_by_name['BoxSecretDeleteResponse']
BoxSecret = _reflection.GeneratedProtocolMessageType('BoxSecret', (_message.Message,), {
  'DESCRIPTOR' : _BOXSECRET,
  '__module__' : 'box.BoxCredential_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.credential.stubs.box.BoxSecret)
  })
_sym_db.RegisterMessage(BoxSecret)

BoxSecretGetRequest = _reflection.GeneratedProtocolMessageType('BoxSecretGetRequest', (_message.Message,), {
  'DESCRIPTOR' : _BOXSECRETGETREQUEST,
  '__module__' : 'box.BoxCredential_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.credential.stubs.box.BoxSecretGetRequest)
  })
_sym_db.RegisterMessage(BoxSecretGetRequest)

BoxSecretCreateRequest = _reflection.GeneratedProtocolMessageType('BoxSecretCreateRequest', (_message.Message,), {
  'DESCRIPTOR' : _BOXSECRETCREATEREQUEST,
  '__module__' : 'box.BoxCredential_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.credential.stubs.box.BoxSecretCreateRequest)
  })
_sym_db.RegisterMessage(BoxSecretCreateRequest)

BoxSecretUpdateRequest = _reflection.GeneratedProtocolMessageType('BoxSecretUpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _BOXSECRETUPDATEREQUEST,
  '__module__' : 'box.BoxCredential_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.credential.stubs.box.BoxSecretUpdateRequest)
  })
_sym_db.RegisterMessage(BoxSecretUpdateRequest)

BoxSecretUpdateResponse = _reflection.GeneratedProtocolMessageType('BoxSecretUpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _BOXSECRETUPDATERESPONSE,
  '__module__' : 'box.BoxCredential_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.credential.stubs.box.BoxSecretUpdateResponse)
  })
_sym_db.RegisterMessage(BoxSecretUpdateResponse)

BoxSecretDeleteRequest = _reflection.GeneratedProtocolMessageType('BoxSecretDeleteRequest', (_message.Message,), {
  'DESCRIPTOR' : _BOXSECRETDELETEREQUEST,
  '__module__' : 'box.BoxCredential_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.credential.stubs.box.BoxSecretDeleteRequest)
  })
_sym_db.RegisterMessage(BoxSecretDeleteRequest)

BoxSecretDeleteResponse = _reflection.GeneratedProtocolMessageType('BoxSecretDeleteResponse', (_message.Message,), {
  'DESCRIPTOR' : _BOXSECRETDELETERESPONSE,
  '__module__' : 'box.BoxCredential_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.credential.stubs.box.BoxSecretDeleteResponse)
  })
_sym_db.RegisterMessage(BoxSecretDeleteResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _BOXSECRET._serialized_start=91
  _BOXSECRET._serialized_end=141
  _BOXSECRETGETREQUEST._serialized_start=143
  _BOXSECRETGETREQUEST._serialized_end=245
  _BOXSECRETCREATEREQUEST._serialized_start=247
  _BOXSECRETCREATEREQUEST._serialized_end=355
  _BOXSECRETUPDATEREQUEST._serialized_start=357
  _BOXSECRETUPDATEREQUEST._serialized_end=483
  _BOXSECRETUPDATERESPONSE._serialized_start=485
  _BOXSECRETUPDATERESPONSE._serialized_end=528
  _BOXSECRETDELETEREQUEST._serialized_start=530
  _BOXSECRETDELETEREQUEST._serialized_end=635
  _BOXSECRETDELETERESPONSE._serialized_start=637
  _BOXSECRETDELETERESPONSE._serialized_end=678
# @@protoc_insertion_point(module_scope)
