# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from airavata_mft_sdk.box import BoxStorage_pb2 as box_dot_BoxStorage__pb2


class BoxStorageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.listBoxStorage = channel.unary_unary(
                '/org.apache.airavata.mft.resource.service.box.BoxStorageService/listBoxStorage',
                request_serializer=box_dot_BoxStorage__pb2.BoxStorageListRequest.SerializeToString,
                response_deserializer=box_dot_BoxStorage__pb2.BoxStorageListResponse.FromString,
                )
        self.getBoxStorage = channel.unary_unary(
                '/org.apache.airavata.mft.resource.service.box.BoxStorageService/getBoxStorage',
                request_serializer=box_dot_BoxStorage__pb2.BoxStorageGetRequest.SerializeToString,
                response_deserializer=box_dot_BoxStorage__pb2.BoxStorage.FromString,
                )
        self.createBoxStorage = channel.unary_unary(
                '/org.apache.airavata.mft.resource.service.box.BoxStorageService/createBoxStorage',
                request_serializer=box_dot_BoxStorage__pb2.BoxStorageCreateRequest.SerializeToString,
                response_deserializer=box_dot_BoxStorage__pb2.BoxStorage.FromString,
                )
        self.updateBoxStorage = channel.unary_unary(
                '/org.apache.airavata.mft.resource.service.box.BoxStorageService/updateBoxStorage',
                request_serializer=box_dot_BoxStorage__pb2.BoxStorageUpdateRequest.SerializeToString,
                response_deserializer=box_dot_BoxStorage__pb2.BoxStorageUpdateResponse.FromString,
                )
        self.deleteBoxStorage = channel.unary_unary(
                '/org.apache.airavata.mft.resource.service.box.BoxStorageService/deleteBoxStorage',
                request_serializer=box_dot_BoxStorage__pb2.BoxStorageDeleteRequest.SerializeToString,
                response_deserializer=box_dot_BoxStorage__pb2.BoxStorageDeleteResponse.FromString,
                )


class BoxStorageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def listBoxStorage(self, request, context):
        """Storage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getBoxStorage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createBoxStorage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateBoxStorage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteBoxStorage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BoxStorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'listBoxStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.listBoxStorage,
                    request_deserializer=box_dot_BoxStorage__pb2.BoxStorageListRequest.FromString,
                    response_serializer=box_dot_BoxStorage__pb2.BoxStorageListResponse.SerializeToString,
            ),
            'getBoxStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.getBoxStorage,
                    request_deserializer=box_dot_BoxStorage__pb2.BoxStorageGetRequest.FromString,
                    response_serializer=box_dot_BoxStorage__pb2.BoxStorage.SerializeToString,
            ),
            'createBoxStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.createBoxStorage,
                    request_deserializer=box_dot_BoxStorage__pb2.BoxStorageCreateRequest.FromString,
                    response_serializer=box_dot_BoxStorage__pb2.BoxStorage.SerializeToString,
            ),
            'updateBoxStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.updateBoxStorage,
                    request_deserializer=box_dot_BoxStorage__pb2.BoxStorageUpdateRequest.FromString,
                    response_serializer=box_dot_BoxStorage__pb2.BoxStorageUpdateResponse.SerializeToString,
            ),
            'deleteBoxStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteBoxStorage,
                    request_deserializer=box_dot_BoxStorage__pb2.BoxStorageDeleteRequest.FromString,
                    response_serializer=box_dot_BoxStorage__pb2.BoxStorageDeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'org.apache.airavata.mft.resource.service.box.BoxStorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BoxStorageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def listBoxStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/org.apache.airavata.mft.resource.service.box.BoxStorageService/listBoxStorage',
            box_dot_BoxStorage__pb2.BoxStorageListRequest.SerializeToString,
            box_dot_BoxStorage__pb2.BoxStorageListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getBoxStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/org.apache.airavata.mft.resource.service.box.BoxStorageService/getBoxStorage',
            box_dot_BoxStorage__pb2.BoxStorageGetRequest.SerializeToString,
            box_dot_BoxStorage__pb2.BoxStorage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createBoxStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/org.apache.airavata.mft.resource.service.box.BoxStorageService/createBoxStorage',
            box_dot_BoxStorage__pb2.BoxStorageCreateRequest.SerializeToString,
            box_dot_BoxStorage__pb2.BoxStorage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def updateBoxStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/org.apache.airavata.mft.resource.service.box.BoxStorageService/updateBoxStorage',
            box_dot_BoxStorage__pb2.BoxStorageUpdateRequest.SerializeToString,
            box_dot_BoxStorage__pb2.BoxStorageUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteBoxStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/org.apache.airavata.mft.resource.service.box.BoxStorageService/deleteBoxStorage',
            box_dot_BoxStorage__pb2.BoxStorageDeleteRequest.SerializeToString,
            box_dot_BoxStorage__pb2.BoxStorageDeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
