# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: box/BoxSecretService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from airavata_mft_sdk.box import BoxCredential_pb2 as box_dot_BoxCredential__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x62ox/BoxSecretService.proto\x12.org.apache.airavata.mft.credential.service.box\x1a\x17\x62ox/BoxCredential.proto2\xf4\x04\n\x10\x42oxSecretService\x12\x8a\x01\n\x0cgetBoxSecret\x12\x41.org.apache.airavata.mft.credential.stubs.box.BoxSecretGetRequest\x1a\x37.org.apache.airavata.mft.credential.stubs.box.BoxSecret\x12\x90\x01\n\x0f\x63reateBoxSecret\x12\x44.org.apache.airavata.mft.credential.stubs.box.BoxSecretCreateRequest\x1a\x37.org.apache.airavata.mft.credential.stubs.box.BoxSecret\x12\x9e\x01\n\x0fupdateBoxSecret\x12\x44.org.apache.airavata.mft.credential.stubs.box.BoxSecretUpdateRequest\x1a\x45.org.apache.airavata.mft.credential.stubs.box.BoxSecretUpdateResponse\x12\x9e\x01\n\x0f\x64\x65leteBoxSecret\x12\x44.org.apache.airavata.mft.credential.stubs.box.BoxSecretDeleteRequest\x1a\x45.org.apache.airavata.mft.credential.stubs.box.BoxSecretDeleteResponseB\x02P\x01\x62\x06proto3')



_BOXSECRETSERVICE = DESCRIPTOR.services_by_name['BoxSecretService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _BOXSECRETSERVICE._serialized_start=104
  _BOXSECRETSERVICE._serialized_end=732
# @@protoc_insertion_point(module_scope)
