# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: http/HTTPStorageService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from airavata_mft_sdk.http import HTTPStorage_pb2 as http_dot_HTTPStorage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dhttp/HTTPStorageService.proto\x12-org.apache.airavata.mft.resource.service.http\x1a\x16http/HTTPStorage.proto2\xf5\x06\n\x12HTTPStorageService\x12\xac\x01\n\x0flistHTTPStorage\x12K.org.apache.airavata.mft.resource.stubs.http.storage.HTTPStorageListRequest\x1aL.org.apache.airavata.mft.resource.stubs.http.storage.HTTPStorageListResponse\x12\x9e\x01\n\x0egetHTTPStorage\x12J.org.apache.airavata.mft.resource.stubs.http.storage.HTTPStorageGetRequest\x1a@.org.apache.airavata.mft.resource.stubs.http.storage.HTTPStorage\x12\xa4\x01\n\x11\x63reateHTTPStorage\x12M.org.apache.airavata.mft.resource.stubs.http.storage.HTTPStorageCreateRequest\x1a@.org.apache.airavata.mft.resource.stubs.http.storage.HTTPStorage\x12\xb2\x01\n\x11updateHTTPStorage\x12M.org.apache.airavata.mft.resource.stubs.http.storage.HTTPStorageUpdateRequest\x1aN.org.apache.airavata.mft.resource.stubs.http.storage.HTTPStorageUpdateResponse\x12\xb2\x01\n\x11\x64\x65leteHTTPStorage\x12M.org.apache.airavata.mft.resource.stubs.http.storage.HTTPStorageDeleteRequest\x1aN.org.apache.airavata.mft.resource.stubs.http.storage.HTTPStorageDeleteResponseB\x02P\x01\x62\x06proto3')



_HTTPSTORAGESERVICE = DESCRIPTOR.services_by_name['HTTPStorageService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _HTTPSTORAGESERVICE._serialized_start=105
  _HTTPSTORAGESERVICE._serialized_end=990
# @@protoc_insertion_point(module_scope)
