# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: http/HttpCredential.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import airavata_mft_sdk.CredCommon_pb2 as CredCommon__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19http/HttpCredential.proto\x12-org.apache.airavata.mft.credential.stubs.http\x1a\x10\x43redCommon.proto\"/\n\tBasicAuth\x12\x10\n\x08userName\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\" \n\tTokenAuth\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x03 \x01(\t\"\xbc\x01\n\nHTTPSecret\x12\x10\n\x08secretId\x18\x01 \x01(\t\x12I\n\x05\x62\x61sic\x18\x02 \x01(\x0b\x32\x38.org.apache.airavata.mft.credential.stubs.http.BasicAuthH\x00\x12I\n\x05token\x18\x03 \x01(\x0b\x32\x38.org.apache.airavata.mft.credential.stubs.http.TokenAuthH\x00\x42\x06\n\x04\x61uth\"g\n\x14HTTPSecretGetRequest\x12\x10\n\x08secretId\x18\x01 \x01(\t\x12=\n\nauthzToken\x18\x02 \x01(\x0b\x32).org.apache.airavata.mft.common.AuthToken\"\xa3\x01\n\x17HTTPSecretCreateRequest\x12I\n\x06secret\x18\x01 \x01(\x0b\x32\x39.org.apache.airavata.mft.credential.stubs.http.HTTPSecret\x12=\n\nauthzToken\x18\x02 \x01(\x0b\x32).org.apache.airavata.mft.common.AuthToken\"\xa3\x01\n\x17HTTPSecretUpdateRequest\x12I\n\x06secret\x18\x01 \x01(\x0b\x32\x39.org.apache.airavata.mft.credential.stubs.http.HTTPSecret\x12=\n\nauthzToken\x18\x02 \x01(\x0b\x32).org.apache.airavata.mft.common.AuthToken\",\n\x18HTTPSecretUpdateResponse\x12\x10\n\x08secretId\x18\x01 \x01(\t\"j\n\x17HTTPSecretDeleteRequest\x12\x10\n\x08secretId\x18\x01 \x01(\t\x12=\n\nauthzToken\x18\x02 \x01(\x0b\x32).org.apache.airavata.mft.common.AuthToken\"*\n\x18HTTPSecretDeleteResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x42\x02P\x01\x62\x06proto3')



_BASICAUTH = DESCRIPTOR.message_types_by_name['BasicAuth']
_TOKENAUTH = DESCRIPTOR.message_types_by_name['TokenAuth']
_HTTPSECRET = DESCRIPTOR.message_types_by_name['HTTPSecret']
_HTTPSECRETGETREQUEST = DESCRIPTOR.message_types_by_name['HTTPSecretGetRequest']
_HTTPSECRETCREATEREQUEST = DESCRIPTOR.message_types_by_name['HTTPSecretCreateRequest']
_HTTPSECRETUPDATEREQUEST = DESCRIPTOR.message_types_by_name['HTTPSecretUpdateRequest']
_HTTPSECRETUPDATERESPONSE = DESCRIPTOR.message_types_by_name['HTTPSecretUpdateResponse']
_HTTPSECRETDELETEREQUEST = DESCRIPTOR.message_types_by_name['HTTPSecretDeleteRequest']
_HTTPSECRETDELETERESPONSE = DESCRIPTOR.message_types_by_name['HTTPSecretDeleteResponse']
BasicAuth = _reflection.GeneratedProtocolMessageType('BasicAuth', (_message.Message,), {
  'DESCRIPTOR' : _BASICAUTH,
  '__module__' : 'http.HttpCredential_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.credential.stubs.http.BasicAuth)
  })
_sym_db.RegisterMessage(BasicAuth)

TokenAuth = _reflection.GeneratedProtocolMessageType('TokenAuth', (_message.Message,), {
  'DESCRIPTOR' : _TOKENAUTH,
  '__module__' : 'http.HttpCredential_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.credential.stubs.http.TokenAuth)
  })
_sym_db.RegisterMessage(TokenAuth)

HTTPSecret = _reflection.GeneratedProtocolMessageType('HTTPSecret', (_message.Message,), {
  'DESCRIPTOR' : _HTTPSECRET,
  '__module__' : 'http.HttpCredential_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.credential.stubs.http.HTTPSecret)
  })
_sym_db.RegisterMessage(HTTPSecret)

HTTPSecretGetRequest = _reflection.GeneratedProtocolMessageType('HTTPSecretGetRequest', (_message.Message,), {
  'DESCRIPTOR' : _HTTPSECRETGETREQUEST,
  '__module__' : 'http.HttpCredential_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.credential.stubs.http.HTTPSecretGetRequest)
  })
_sym_db.RegisterMessage(HTTPSecretGetRequest)

HTTPSecretCreateRequest = _reflection.GeneratedProtocolMessageType('HTTPSecretCreateRequest', (_message.Message,), {
  'DESCRIPTOR' : _HTTPSECRETCREATEREQUEST,
  '__module__' : 'http.HttpCredential_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.credential.stubs.http.HTTPSecretCreateRequest)
  })
_sym_db.RegisterMessage(HTTPSecretCreateRequest)

HTTPSecretUpdateRequest = _reflection.GeneratedProtocolMessageType('HTTPSecretUpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _HTTPSECRETUPDATEREQUEST,
  '__module__' : 'http.HttpCredential_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.credential.stubs.http.HTTPSecretUpdateRequest)
  })
_sym_db.RegisterMessage(HTTPSecretUpdateRequest)

HTTPSecretUpdateResponse = _reflection.GeneratedProtocolMessageType('HTTPSecretUpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _HTTPSECRETUPDATERESPONSE,
  '__module__' : 'http.HttpCredential_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.credential.stubs.http.HTTPSecretUpdateResponse)
  })
_sym_db.RegisterMessage(HTTPSecretUpdateResponse)

HTTPSecretDeleteRequest = _reflection.GeneratedProtocolMessageType('HTTPSecretDeleteRequest', (_message.Message,), {
  'DESCRIPTOR' : _HTTPSECRETDELETEREQUEST,
  '__module__' : 'http.HttpCredential_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.credential.stubs.http.HTTPSecretDeleteRequest)
  })
_sym_db.RegisterMessage(HTTPSecretDeleteRequest)

HTTPSecretDeleteResponse = _reflection.GeneratedProtocolMessageType('HTTPSecretDeleteResponse', (_message.Message,), {
  'DESCRIPTOR' : _HTTPSECRETDELETERESPONSE,
  '__module__' : 'http.HttpCredential_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.credential.stubs.http.HTTPSecretDeleteResponse)
  })
_sym_db.RegisterMessage(HTTPSecretDeleteResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _BASICAUTH._serialized_start=94
  _BASICAUTH._serialized_end=141
  _TOKENAUTH._serialized_start=143
  _TOKENAUTH._serialized_end=175
  _HTTPSECRET._serialized_start=178
  _HTTPSECRET._serialized_end=366
  _HTTPSECRETGETREQUEST._serialized_start=368
  _HTTPSECRETGETREQUEST._serialized_end=471
  _HTTPSECRETCREATEREQUEST._serialized_start=474
  _HTTPSECRETCREATEREQUEST._serialized_end=637
  _HTTPSECRETUPDATEREQUEST._serialized_start=640
  _HTTPSECRETUPDATEREQUEST._serialized_end=803
  _HTTPSECRETUPDATERESPONSE._serialized_start=805
  _HTTPSECRETUPDATERESPONSE._serialized_end=849
  _HTTPSECRETDELETEREQUEST._serialized_start=851
  _HTTPSECRETDELETEREQUEST._serialized_end=957
  _HTTPSECRETDELETERESPONSE._serialized_start=959
  _HTTPSECRETDELETERESPONSE._serialized_end=1001
# @@protoc_insertion_point(module_scope)
