# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: azure/AzureSecretService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from azure import AzureCredential_pb2 as azure_dot_AzureCredential__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61zure/AzureSecretService.proto\x12\x30org.apache.airavata.mft.credential.service.azure\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1b\x61zure/AzureCredential.proto2\xa8\x05\n\x12\x41zureSecretService\x12\xb0\x01\n\x0egetAzureSecret\x12\x45.org.apache.airavata.mft.credential.stubs.azure.AzureSecretGetRequest\x1a;.org.apache.airavata.mft.credential.stubs.azure.AzureSecret\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1.0/secret/azure\x12\xb6\x01\n\x11\x63reateAzureSecret\x12H.org.apache.airavata.mft.credential.stubs.azure.AzureSecretCreateRequest\x1a;.org.apache.airavata.mft.credential.stubs.azure.AzureSecret\"\x1a\x82\xd3\xe4\x93\x02\x14\"\x12/v1.0/secret/azure\x12\x91\x01\n\x11updateAzureSecret\x12H.org.apache.airavata.mft.credential.stubs.azure.AzureSecretUpdateRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14\x1a\x12/v1.0/secret/azure\x12\x91\x01\n\x11\x64\x65leteAzureSecret\x12H.org.apache.airavata.mft.credential.stubs.azure.AzureSecretDeleteRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/v1.0/secret/azureB\x02P\x01\x62\x06proto3')



_AZURESECRETSERVICE = DESCRIPTOR.services_by_name['AzureSecretService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _AZURESECRETSERVICE.methods_by_name['getAzureSecret']._options = None
  _AZURESECRETSERVICE.methods_by_name['getAzureSecret']._serialized_options = b'\202\323\344\223\002\024\022\022/v1.0/secret/azure'
  _AZURESECRETSERVICE.methods_by_name['createAzureSecret']._options = None
  _AZURESECRETSERVICE.methods_by_name['createAzureSecret']._serialized_options = b'\202\323\344\223\002\024\"\022/v1.0/secret/azure'
  _AZURESECRETSERVICE.methods_by_name['updateAzureSecret']._options = None
  _AZURESECRETSERVICE.methods_by_name['updateAzureSecret']._serialized_options = b'\202\323\344\223\002\024\032\022/v1.0/secret/azure'
  _AZURESECRETSERVICE.methods_by_name['deleteAzureSecret']._options = None
  _AZURESECRETSERVICE.methods_by_name['deleteAzureSecret']._serialized_options = b'\202\323\344\223\002\024*\022/v1.0/secret/azure'
  _AZURESECRETSERVICE._serialized_start=173
  _AZURESECRETSERVICE._serialized_end=853
# @@protoc_insertion_point(module_scope)
