# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: swift/SwiftStorageService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from airavata_mft_sdk.swift import SwiftStorage_pb2 as swift_dot_SwiftStorage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fswift/SwiftStorageService.proto\x12.org.apache.airavata.mft.resource.service.swift\x1a\x18swift/SwiftStorage.proto2\x8f\x07\n\x13SwiftStorageService\x12\xb1\x01\n\x10listSwiftStorage\x12M.org.apache.airavata.mft.resource.stubs.swift.storage.SwiftStorageListRequest\x1aN.org.apache.airavata.mft.resource.stubs.swift.storage.SwiftStorageListResponse\x12\xa3\x01\n\x0fgetSwiftStorage\x12L.org.apache.airavata.mft.resource.stubs.swift.storage.SwiftStorageGetRequest\x1a\x42.org.apache.airavata.mft.resource.stubs.swift.storage.SwiftStorage\x12\xa9\x01\n\x12\x63reateSwiftStorage\x12O.org.apache.airavata.mft.resource.stubs.swift.storage.SwiftStorageCreateRequest\x1a\x42.org.apache.airavata.mft.resource.stubs.swift.storage.SwiftStorage\x12\xb7\x01\n\x12updateSwiftStorage\x12O.org.apache.airavata.mft.resource.stubs.swift.storage.SwiftStorageUpdateRequest\x1aP.org.apache.airavata.mft.resource.stubs.swift.storage.SwiftStorageUpdateResponse\x12\xb7\x01\n\x12\x64\x65leteSwiftStorage\x12O.org.apache.airavata.mft.resource.stubs.swift.storage.SwiftStorageDeleteRequest\x1aP.org.apache.airavata.mft.resource.stubs.swift.storage.SwiftStorageDeleteResponseB\x02P\x01\x62\x06proto3')



_SWIFTSTORAGESERVICE = DESCRIPTOR.services_by_name['SwiftStorageService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _SWIFTSTORAGESERVICE._serialized_start=110
  _SWIFTSTORAGESERVICE._serialized_end=1021
# @@protoc_insertion_point(module_scope)
