# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import mft_backend.resource_service.ResourceService_pb2 as ResourceService__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class ResourceServiceStub(object):
  """SCP Storage
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getSCPStorage = channel.unary_unary(
        '/org.apache.airavata.mft.resource.service.ResourceService/getSCPStorage',
        request_serializer=ResourceService__pb2.SCPStorageGetRequest.SerializeToString,
        response_deserializer=ResourceService__pb2.SCPStorage.FromString,
        )
    self.createSCPStorage = channel.unary_unary(
        '/org.apache.airavata.mft.resource.service.ResourceService/createSCPStorage',
        request_serializer=ResourceService__pb2.SCPStorageCreateRequest.SerializeToString,
        response_deserializer=ResourceService__pb2.SCPStorage.FromString,
        )
    self.updateSCPStorage = channel.unary_unary(
        '/org.apache.airavata.mft.resource.service.ResourceService/updateSCPStorage',
        request_serializer=ResourceService__pb2.SCPStorageUpdateRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.deleteSCPStorage = channel.unary_unary(
        '/org.apache.airavata.mft.resource.service.ResourceService/deleteSCPStorage',
        request_serializer=ResourceService__pb2.SCPStorageDeleteRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.getSCPResource = channel.unary_unary(
        '/org.apache.airavata.mft.resource.service.ResourceService/getSCPResource',
        request_serializer=ResourceService__pb2.SCPResourceGetRequest.SerializeToString,
        response_deserializer=ResourceService__pb2.SCPResource.FromString,
        )
    self.createSCPResource = channel.unary_unary(
        '/org.apache.airavata.mft.resource.service.ResourceService/createSCPResource',
        request_serializer=ResourceService__pb2.SCPResourceCreateRequest.SerializeToString,
        response_deserializer=ResourceService__pb2.SCPResource.FromString,
        )
    self.updateSCPResource = channel.unary_unary(
        '/org.apache.airavata.mft.resource.service.ResourceService/updateSCPResource',
        request_serializer=ResourceService__pb2.SCPResourceUpdateRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.deleteSCPResource = channel.unary_unary(
        '/org.apache.airavata.mft.resource.service.ResourceService/deleteSCPResource',
        request_serializer=ResourceService__pb2.SCPResourceDeleteRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.getLocalResource = channel.unary_unary(
        '/org.apache.airavata.mft.resource.service.ResourceService/getLocalResource',
        request_serializer=ResourceService__pb2.LocalResourceGetRequest.SerializeToString,
        response_deserializer=ResourceService__pb2.LocalResource.FromString,
        )
    self.createLocalResource = channel.unary_unary(
        '/org.apache.airavata.mft.resource.service.ResourceService/createLocalResource',
        request_serializer=ResourceService__pb2.LocalResourceCreateRequest.SerializeToString,
        response_deserializer=ResourceService__pb2.LocalResource.FromString,
        )
    self.updateLocalResource = channel.unary_unary(
        '/org.apache.airavata.mft.resource.service.ResourceService/updateLocalResource',
        request_serializer=ResourceService__pb2.LocalResourceUpdateRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.deleteLocalResource = channel.unary_unary(
        '/org.apache.airavata.mft.resource.service.ResourceService/deleteLocalResource',
        request_serializer=ResourceService__pb2.LocalResourceDeleteRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class ResourceServiceServicer(object):
  """SCP Storage
  """

  def getSCPStorage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def createSCPStorage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def updateSCPStorage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def deleteSCPStorage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getSCPResource(self, request, context):
    """SCP Resource

    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def createSCPResource(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def updateSCPResource(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def deleteSCPResource(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getLocalResource(self, request, context):
    """Local Resource

    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def createLocalResource(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def updateLocalResource(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def deleteLocalResource(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ResourceServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getSCPStorage': grpc.unary_unary_rpc_method_handler(
          servicer.getSCPStorage,
          request_deserializer=ResourceService__pb2.SCPStorageGetRequest.FromString,
          response_serializer=ResourceService__pb2.SCPStorage.SerializeToString,
      ),
      'createSCPStorage': grpc.unary_unary_rpc_method_handler(
          servicer.createSCPStorage,
          request_deserializer=ResourceService__pb2.SCPStorageCreateRequest.FromString,
          response_serializer=ResourceService__pb2.SCPStorage.SerializeToString,
      ),
      'updateSCPStorage': grpc.unary_unary_rpc_method_handler(
          servicer.updateSCPStorage,
          request_deserializer=ResourceService__pb2.SCPStorageUpdateRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'deleteSCPStorage': grpc.unary_unary_rpc_method_handler(
          servicer.deleteSCPStorage,
          request_deserializer=ResourceService__pb2.SCPStorageDeleteRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'getSCPResource': grpc.unary_unary_rpc_method_handler(
          servicer.getSCPResource,
          request_deserializer=ResourceService__pb2.SCPResourceGetRequest.FromString,
          response_serializer=ResourceService__pb2.SCPResource.SerializeToString,
      ),
      'createSCPResource': grpc.unary_unary_rpc_method_handler(
          servicer.createSCPResource,
          request_deserializer=ResourceService__pb2.SCPResourceCreateRequest.FromString,
          response_serializer=ResourceService__pb2.SCPResource.SerializeToString,
      ),
      'updateSCPResource': grpc.unary_unary_rpc_method_handler(
          servicer.updateSCPResource,
          request_deserializer=ResourceService__pb2.SCPResourceUpdateRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'deleteSCPResource': grpc.unary_unary_rpc_method_handler(
          servicer.deleteSCPResource,
          request_deserializer=ResourceService__pb2.SCPResourceDeleteRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'getLocalResource': grpc.unary_unary_rpc_method_handler(
          servicer.getLocalResource,
          request_deserializer=ResourceService__pb2.LocalResourceGetRequest.FromString,
          response_serializer=ResourceService__pb2.LocalResource.SerializeToString,
      ),
      'createLocalResource': grpc.unary_unary_rpc_method_handler(
          servicer.createLocalResource,
          request_deserializer=ResourceService__pb2.LocalResourceCreateRequest.FromString,
          response_serializer=ResourceService__pb2.LocalResource.SerializeToString,
      ),
      'updateLocalResource': grpc.unary_unary_rpc_method_handler(
          servicer.updateLocalResource,
          request_deserializer=ResourceService__pb2.LocalResourceUpdateRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'deleteLocalResource': grpc.unary_unary_rpc_method_handler(
          servicer.deleteLocalResource,
          request_deserializer=ResourceService__pb2.LocalResourceDeleteRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'org.apache.airavata.mft.resource.service.ResourceService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
