# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from airavata_mft_sdk.dropbox import DropboxStorage_pb2 as dropbox_dot_DropboxStorage__pb2


class DropboxStorageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.listDropboxStorage = channel.unary_unary(
                '/org.apache.airavata.mft.resource.service.dropbox.DropboxStorageService/listDropboxStorage',
                request_serializer=dropbox_dot_DropboxStorage__pb2.DropboxStorageListRequest.SerializeToString,
                response_deserializer=dropbox_dot_DropboxStorage__pb2.DropboxStorageListResponse.FromString,
                )
        self.getDropboxStorage = channel.unary_unary(
                '/org.apache.airavata.mft.resource.service.dropbox.DropboxStorageService/getDropboxStorage',
                request_serializer=dropbox_dot_DropboxStorage__pb2.DropboxStorageGetRequest.SerializeToString,
                response_deserializer=dropbox_dot_DropboxStorage__pb2.DropboxStorage.FromString,
                )
        self.createDropboxStorage = channel.unary_unary(
                '/org.apache.airavata.mft.resource.service.dropbox.DropboxStorageService/createDropboxStorage',
                request_serializer=dropbox_dot_DropboxStorage__pb2.DropboxStorageCreateRequest.SerializeToString,
                response_deserializer=dropbox_dot_DropboxStorage__pb2.DropboxStorage.FromString,
                )
        self.updateDropboxStorage = channel.unary_unary(
                '/org.apache.airavata.mft.resource.service.dropbox.DropboxStorageService/updateDropboxStorage',
                request_serializer=dropbox_dot_DropboxStorage__pb2.DropboxStorageUpdateRequest.SerializeToString,
                response_deserializer=dropbox_dot_DropboxStorage__pb2.DropboxStorageUpdateResponse.FromString,
                )
        self.deleteDropboxStorage = channel.unary_unary(
                '/org.apache.airavata.mft.resource.service.dropbox.DropboxStorageService/deleteDropboxStorage',
                request_serializer=dropbox_dot_DropboxStorage__pb2.DropboxStorageDeleteRequest.SerializeToString,
                response_deserializer=dropbox_dot_DropboxStorage__pb2.DropboxStorageDeleteResponse.FromString,
                )


class DropboxStorageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def listDropboxStorage(self, request, context):
        """Storage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getDropboxStorage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createDropboxStorage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateDropboxStorage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteDropboxStorage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DropboxStorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'listDropboxStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.listDropboxStorage,
                    request_deserializer=dropbox_dot_DropboxStorage__pb2.DropboxStorageListRequest.FromString,
                    response_serializer=dropbox_dot_DropboxStorage__pb2.DropboxStorageListResponse.SerializeToString,
            ),
            'getDropboxStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.getDropboxStorage,
                    request_deserializer=dropbox_dot_DropboxStorage__pb2.DropboxStorageGetRequest.FromString,
                    response_serializer=dropbox_dot_DropboxStorage__pb2.DropboxStorage.SerializeToString,
            ),
            'createDropboxStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.createDropboxStorage,
                    request_deserializer=dropbox_dot_DropboxStorage__pb2.DropboxStorageCreateRequest.FromString,
                    response_serializer=dropbox_dot_DropboxStorage__pb2.DropboxStorage.SerializeToString,
            ),
            'updateDropboxStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.updateDropboxStorage,
                    request_deserializer=dropbox_dot_DropboxStorage__pb2.DropboxStorageUpdateRequest.FromString,
                    response_serializer=dropbox_dot_DropboxStorage__pb2.DropboxStorageUpdateResponse.SerializeToString,
            ),
            'deleteDropboxStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteDropboxStorage,
                    request_deserializer=dropbox_dot_DropboxStorage__pb2.DropboxStorageDeleteRequest.FromString,
                    response_serializer=dropbox_dot_DropboxStorage__pb2.DropboxStorageDeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'org.apache.airavata.mft.resource.service.dropbox.DropboxStorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DropboxStorageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def listDropboxStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/org.apache.airavata.mft.resource.service.dropbox.DropboxStorageService/listDropboxStorage',
            dropbox_dot_DropboxStorage__pb2.DropboxStorageListRequest.SerializeToString,
            dropbox_dot_DropboxStorage__pb2.DropboxStorageListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getDropboxStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/org.apache.airavata.mft.resource.service.dropbox.DropboxStorageService/getDropboxStorage',
            dropbox_dot_DropboxStorage__pb2.DropboxStorageGetRequest.SerializeToString,
            dropbox_dot_DropboxStorage__pb2.DropboxStorage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createDropboxStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/org.apache.airavata.mft.resource.service.dropbox.DropboxStorageService/createDropboxStorage',
            dropbox_dot_DropboxStorage__pb2.DropboxStorageCreateRequest.SerializeToString,
            dropbox_dot_DropboxStorage__pb2.DropboxStorage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def updateDropboxStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/org.apache.airavata.mft.resource.service.dropbox.DropboxStorageService/updateDropboxStorage',
            dropbox_dot_DropboxStorage__pb2.DropboxStorageUpdateRequest.SerializeToString,
            dropbox_dot_DropboxStorage__pb2.DropboxStorageUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteDropboxStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/org.apache.airavata.mft.resource.service.dropbox.DropboxStorageService/deleteDropboxStorage',
            dropbox_dot_DropboxStorage__pb2.DropboxStorageDeleteRequest.SerializeToString,
            dropbox_dot_DropboxStorage__pb2.DropboxStorageDeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
