# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: odata/ODataCredential.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import airavata_mft_sdk.CredCommon_pb2 as CredCommon__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bodata/ODataCredential.proto\x12.org.apache.airavata.mft.credential.stubs.odata\x1a\x10\x43redCommon.proto\"C\n\x0bODataSecret\x12\x10\n\x08secretId\x18\x01 \x01(\t\x12\x10\n\x08userName\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"h\n\x15ODataSecretGetRequest\x12\x10\n\x08secretId\x18\x01 \x01(\t\x12=\n\nauthzToken\x18\x02 \x01(\x0b\x32).org.apache.airavata.mft.common.AuthToken\"}\n\x18ODataSecretCreateRequest\x12\x10\n\x08userName\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12=\n\nauthzToken\x18\x03 \x01(\x0b\x32).org.apache.airavata.mft.common.AuthToken\"\x8f\x01\n\x18ODataSecretUpdateRequest\x12\x10\n\x08secretId\x18\x01 \x01(\t\x12\x10\n\x08userName\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12=\n\nauthzToken\x18\x04 \x01(\x0b\x32).org.apache.airavata.mft.common.AuthToken\"-\n\x19ODataSecretUpdateResponse\x12\x10\n\x08secretId\x18\x01 \x01(\t\"k\n\x18ODataSecretDeleteRequest\x12\x10\n\x08secretId\x18\x01 \x01(\t\x12=\n\nauthzToken\x18\x02 \x01(\x0b\x32).org.apache.airavata.mft.common.AuthToken\"+\n\x19ODataSecretDeleteResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x42\x02P\x01\x62\x06proto3')



_ODATASECRET = DESCRIPTOR.message_types_by_name['ODataSecret']
_ODATASECRETGETREQUEST = DESCRIPTOR.message_types_by_name['ODataSecretGetRequest']
_ODATASECRETCREATEREQUEST = DESCRIPTOR.message_types_by_name['ODataSecretCreateRequest']
_ODATASECRETUPDATEREQUEST = DESCRIPTOR.message_types_by_name['ODataSecretUpdateRequest']
_ODATASECRETUPDATERESPONSE = DESCRIPTOR.message_types_by_name['ODataSecretUpdateResponse']
_ODATASECRETDELETEREQUEST = DESCRIPTOR.message_types_by_name['ODataSecretDeleteRequest']
_ODATASECRETDELETERESPONSE = DESCRIPTOR.message_types_by_name['ODataSecretDeleteResponse']
ODataSecret = _reflection.GeneratedProtocolMessageType('ODataSecret', (_message.Message,), {
  'DESCRIPTOR' : _ODATASECRET,
  '__module__' : 'odata.ODataCredential_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.credential.stubs.odata.ODataSecret)
  })
_sym_db.RegisterMessage(ODataSecret)

ODataSecretGetRequest = _reflection.GeneratedProtocolMessageType('ODataSecretGetRequest', (_message.Message,), {
  'DESCRIPTOR' : _ODATASECRETGETREQUEST,
  '__module__' : 'odata.ODataCredential_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.credential.stubs.odata.ODataSecretGetRequest)
  })
_sym_db.RegisterMessage(ODataSecretGetRequest)

ODataSecretCreateRequest = _reflection.GeneratedProtocolMessageType('ODataSecretCreateRequest', (_message.Message,), {
  'DESCRIPTOR' : _ODATASECRETCREATEREQUEST,
  '__module__' : 'odata.ODataCredential_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.credential.stubs.odata.ODataSecretCreateRequest)
  })
_sym_db.RegisterMessage(ODataSecretCreateRequest)

ODataSecretUpdateRequest = _reflection.GeneratedProtocolMessageType('ODataSecretUpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _ODATASECRETUPDATEREQUEST,
  '__module__' : 'odata.ODataCredential_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.credential.stubs.odata.ODataSecretUpdateRequest)
  })
_sym_db.RegisterMessage(ODataSecretUpdateRequest)

ODataSecretUpdateResponse = _reflection.GeneratedProtocolMessageType('ODataSecretUpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _ODATASECRETUPDATERESPONSE,
  '__module__' : 'odata.ODataCredential_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.credential.stubs.odata.ODataSecretUpdateResponse)
  })
_sym_db.RegisterMessage(ODataSecretUpdateResponse)

ODataSecretDeleteRequest = _reflection.GeneratedProtocolMessageType('ODataSecretDeleteRequest', (_message.Message,), {
  'DESCRIPTOR' : _ODATASECRETDELETEREQUEST,
  '__module__' : 'odata.ODataCredential_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.credential.stubs.odata.ODataSecretDeleteRequest)
  })
_sym_db.RegisterMessage(ODataSecretDeleteRequest)

ODataSecretDeleteResponse = _reflection.GeneratedProtocolMessageType('ODataSecretDeleteResponse', (_message.Message,), {
  'DESCRIPTOR' : _ODATASECRETDELETERESPONSE,
  '__module__' : 'odata.ODataCredential_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.credential.stubs.odata.ODataSecretDeleteResponse)
  })
_sym_db.RegisterMessage(ODataSecretDeleteResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _ODATASECRET._serialized_start=97
  _ODATASECRET._serialized_end=164
  _ODATASECRETGETREQUEST._serialized_start=166
  _ODATASECRETGETREQUEST._serialized_end=270
  _ODATASECRETCREATEREQUEST._serialized_start=272
  _ODATASECRETCREATEREQUEST._serialized_end=397
  _ODATASECRETUPDATEREQUEST._serialized_start=400
  _ODATASECRETUPDATEREQUEST._serialized_end=543
  _ODATASECRETUPDATERESPONSE._serialized_start=545
  _ODATASECRETUPDATERESPONSE._serialized_end=590
  _ODATASECRETDELETEREQUEST._serialized_start=592
  _ODATASECRETDELETEREQUEST._serialized_end=699
  _ODATASECRETDELETERESPONSE._serialized_start=701
  _ODATASECRETDELETERESPONSE._serialized_end=744
# @@protoc_insertion_point(module_scope)
