# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: local/LocalStorage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18local/LocalStorage.proto\x12\x34org.apache.airavata.mft.resource.stubs.local.storage\"@\n\x0cLocalStorage\x12\x11\n\tstorageId\x18\x01 \x01(\t\x12\x0f\n\x07\x61gentId\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"8\n\x17LocalStorageListRequest\x12\x0e\n\x06offset\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\"p\n\x18LocalStorageListResponse\x12T\n\x08storages\x18\x01 \x03(\x0b\x32\x42.org.apache.airavata.mft.resource.stubs.local.storage.LocalStorage\"+\n\x16LocalStorageGetRequest\x12\x11\n\tstorageId\x18\x01 \x01(\t\"M\n\x19LocalStorageCreateRequest\x12\x0f\n\x07\x61gentId\x18\x01 \x01(\t\x12\x11\n\tstorageId\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"M\n\x19LocalStorageUpdateRequest\x12\x11\n\tstorageId\x18\x01 \x01(\t\x12\x0f\n\x07\x61gentId\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"/\n\x1aLocalStorageUpdateResponse\x12\x11\n\tstorageId\x18\x01 \x01(\t\".\n\x19LocalStorageDeleteRequest\x12\x11\n\tstorageId\x18\x01 \x01(\t\",\n\x1aLocalStorageDeleteResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x42\x02P\x01\x62\x06proto3')



_LOCALSTORAGE = DESCRIPTOR.message_types_by_name['LocalStorage']
_LOCALSTORAGELISTREQUEST = DESCRIPTOR.message_types_by_name['LocalStorageListRequest']
_LOCALSTORAGELISTRESPONSE = DESCRIPTOR.message_types_by_name['LocalStorageListResponse']
_LOCALSTORAGEGETREQUEST = DESCRIPTOR.message_types_by_name['LocalStorageGetRequest']
_LOCALSTORAGECREATEREQUEST = DESCRIPTOR.message_types_by_name['LocalStorageCreateRequest']
_LOCALSTORAGEUPDATEREQUEST = DESCRIPTOR.message_types_by_name['LocalStorageUpdateRequest']
_LOCALSTORAGEUPDATERESPONSE = DESCRIPTOR.message_types_by_name['LocalStorageUpdateResponse']
_LOCALSTORAGEDELETEREQUEST = DESCRIPTOR.message_types_by_name['LocalStorageDeleteRequest']
_LOCALSTORAGEDELETERESPONSE = DESCRIPTOR.message_types_by_name['LocalStorageDeleteResponse']
LocalStorage = _reflection.GeneratedProtocolMessageType('LocalStorage', (_message.Message,), {
  'DESCRIPTOR' : _LOCALSTORAGE,
  '__module__' : 'local.LocalStorage_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.resource.stubs.local.storage.LocalStorage)
  })
_sym_db.RegisterMessage(LocalStorage)

LocalStorageListRequest = _reflection.GeneratedProtocolMessageType('LocalStorageListRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOCALSTORAGELISTREQUEST,
  '__module__' : 'local.LocalStorage_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.resource.stubs.local.storage.LocalStorageListRequest)
  })
_sym_db.RegisterMessage(LocalStorageListRequest)

LocalStorageListResponse = _reflection.GeneratedProtocolMessageType('LocalStorageListResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOCALSTORAGELISTRESPONSE,
  '__module__' : 'local.LocalStorage_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.resource.stubs.local.storage.LocalStorageListResponse)
  })
_sym_db.RegisterMessage(LocalStorageListResponse)

LocalStorageGetRequest = _reflection.GeneratedProtocolMessageType('LocalStorageGetRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOCALSTORAGEGETREQUEST,
  '__module__' : 'local.LocalStorage_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.resource.stubs.local.storage.LocalStorageGetRequest)
  })
_sym_db.RegisterMessage(LocalStorageGetRequest)

LocalStorageCreateRequest = _reflection.GeneratedProtocolMessageType('LocalStorageCreateRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOCALSTORAGECREATEREQUEST,
  '__module__' : 'local.LocalStorage_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.resource.stubs.local.storage.LocalStorageCreateRequest)
  })
_sym_db.RegisterMessage(LocalStorageCreateRequest)

LocalStorageUpdateRequest = _reflection.GeneratedProtocolMessageType('LocalStorageUpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOCALSTORAGEUPDATEREQUEST,
  '__module__' : 'local.LocalStorage_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.resource.stubs.local.storage.LocalStorageUpdateRequest)
  })
_sym_db.RegisterMessage(LocalStorageUpdateRequest)

LocalStorageUpdateResponse = _reflection.GeneratedProtocolMessageType('LocalStorageUpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOCALSTORAGEUPDATERESPONSE,
  '__module__' : 'local.LocalStorage_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.resource.stubs.local.storage.LocalStorageUpdateResponse)
  })
_sym_db.RegisterMessage(LocalStorageUpdateResponse)

LocalStorageDeleteRequest = _reflection.GeneratedProtocolMessageType('LocalStorageDeleteRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOCALSTORAGEDELETEREQUEST,
  '__module__' : 'local.LocalStorage_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.resource.stubs.local.storage.LocalStorageDeleteRequest)
  })
_sym_db.RegisterMessage(LocalStorageDeleteRequest)

LocalStorageDeleteResponse = _reflection.GeneratedProtocolMessageType('LocalStorageDeleteResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOCALSTORAGEDELETERESPONSE,
  '__module__' : 'local.LocalStorage_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.airavata.mft.resource.stubs.local.storage.LocalStorageDeleteResponse)
  })
_sym_db.RegisterMessage(LocalStorageDeleteResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _LOCALSTORAGE._serialized_start=82
  _LOCALSTORAGE._serialized_end=146
  _LOCALSTORAGELISTREQUEST._serialized_start=148
  _LOCALSTORAGELISTREQUEST._serialized_end=204
  _LOCALSTORAGELISTRESPONSE._serialized_start=206
  _LOCALSTORAGELISTRESPONSE._serialized_end=318
  _LOCALSTORAGEGETREQUEST._serialized_start=320
  _LOCALSTORAGEGETREQUEST._serialized_end=363
  _LOCALSTORAGECREATEREQUEST._serialized_start=365
  _LOCALSTORAGECREATEREQUEST._serialized_end=442
  _LOCALSTORAGEUPDATEREQUEST._serialized_start=444
  _LOCALSTORAGEUPDATEREQUEST._serialized_end=521
  _LOCALSTORAGEUPDATERESPONSE._serialized_start=523
  _LOCALSTORAGEUPDATERESPONSE._serialized_end=570
  _LOCALSTORAGEDELETEREQUEST._serialized_start=572
  _LOCALSTORAGEDELETEREQUEST._serialized_end=618
  _LOCALSTORAGEDELETERESPONSE._serialized_start=620
  _LOCALSTORAGEDELETERESPONSE._serialized_end=664
# @@protoc_insertion_point(module_scope)
